# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /Main_Page
        permanent: true

main:
    path:      /Main_Page
    defaults:  { _controller: AppBundle:Main:home }
    prefix: /src

events:
    path:      /Events
    defaults:  { _controller: AppBundle:Main:event }
    prefix: /src

# // TODO ugly handling of none selection, uses defaults instead
nopeople:
    path:      /People:
    defaults:  { _controller: AppBundle:Main:noPeople }
    prefix: /src

people:
    path:      /People:{people}
    defaults:  { _controller: AppBundle:Main:people }
    prefix: /src

index:
    path:      /index.php
    defaults:  { _controller: AppBundle:Main:index }
    prefix: /src

# Bundle FOS

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

