# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /Main_Page
        permanent: true

main:
    path:      /Main_Page
    defaults:  { _controller: AppBundle:Main:home }
    prefix: /src

events:
    path:      /Events
    defaults:  { _controller: AppBundle:Main:event }
    prefix: /src

# Change route for user management and get linked directly without changing html

people:
    path:      /People:{people}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_show
        permanent: true

index:
    path:      /index.php
    defaults:  { _controller: AppBundle:Main:index }
    prefix: /src

search:
    path: /search
    defaults: { _controller: AppBundle:Search:search }
    prefix: /src

# Bundle FOS

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

