# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /Main_Page
        permanent: true

main:
    path:      /Main_Page
    defaults:  { _controller: AppBundle:Main:show }
    prefix: /src
